FROM ubuntu



ARG ARG_APP_EXTERNAL_LISTEN_IP
ENV APP_EXTERNAL_LISTEN_IP=ARG_APP_EXTERNAL_LISTEN_IP

ARG ARG_APP_EXTERNAL_LISTEN_PORT
ENV APP_EXTERNAL_LISTEN_PORT=ARG_APP_EXTERNAL_LISTEN_PORT


ARG ARG_APP_RELOAD_PATH
ENV APP_RELOAD_PATH=ARG_APP_RELOAD_PATH

ARG ARG_LISTEN_PORT
ENV LISTEN_PORT=ARG_LISTEN_PORT

ARG ARG_GITHUB_HOOK_SECRET
ENV GITHUB_HOOK_SECRET=ARG_GITHUB_HOOK_SECRET

ARG ARG_GITHUB_WEBHOOK_PATH
ENV GITHUB_WEBHOOK_PATH=ARG_GITHUB_WEBHOOK_PATH

ARG ARG_GITHUB_URL
ENV GITHUB_URL=ARG_GITHUB_URL

ARG ARG_GITHUB_EXTERNAL_LISTEN_PORT
ENV GITHUB_EXTERNAL_LISTEN_PORT=ARG_GITHUB_EXTERNAL_LISTEN_PORT

ARG ARG_GITHUB_EXTERNAL_LISTEN_IP
ENV GITHUB_EXTERNAL_LISTEN_IP=ARG_GITHUB_EXTERNAL_LISTEN_IP

RUN apt -yq update
RUN apt -yq install nodejs
RUN apt -yq install npm
RUN apt -yq install wget
RUN apt -yq install git
RUN npm install n -g
RUN n latest

RUN npm install yarn -g
RUN npm install -g nodemon
RUN npm install -g parcel
COPY ./refresher/package.json /tmp
COPY ./refresher/gitserver.js /tmp
RUN cd /tmp && npm install 
EXPOSE 3000
EXPOSE 4500
COPY startUpScript.sh /tmp
CMD ["chmod", "+x",  "/tmp/gitRefresh.sh"]
RUN /bin/bash -c 'chmod +x /tmp/startUpScript.sh&& chmod +x /tmp/gitRefresh.sh'
ENTRYPOINT ["/tmp/startUpScript.sh"]

