version: "3.5"
services:
    test-live:
        image: "invictieu/live-reload:0.1.3"
        container_name: test-live
        hostname: test-live
        #user: "node"
        #working_dir: /node/app
        environment:
        - NODE_ENV=production
        - GITHUB_URL=https://github.com/Invicti/setip_landing.git
        - GITHUB_HOOK_SECRET="changethisDa#$it"
        - DOCKER_APP_NAME="live-reload"
        - GITHUB_WEBHOOK_PATH="/githook"
        - APP_RELOAD_PATH=
        - APP_EXTERNAL_LISTEN_IP=0.0.0.0
        - GITHUB_EXTERNAL_LISTEN_IP=0.0.0.0
        - APP_EXTERNAL_LISTEN_PORT=3000
        - GITHUB_EXTERNAL_LISTEN_PORT=4500
    #   volumes:
    #    - /root/work/makeconfigs/etc/PCSD4Gd/test:/node
        expose:
        - 3000